TimeAttendence/Controllers/LoginAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TimeAttendence.Models;

namespace TimeAttendence.Controllers
{
    public class LoginAccountController : Controller
    {
        // GET: Account
        public ActionResult Login()
        {
            return View();
        }

        //Login to information
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            if (!IsCorrectSystemAdmin(model))
            {
                ModelState.AddModelError("","Invalid username and password");
                return View("Login");
            }

            Session["username"] = model.Username;
            return RedirectToAction("Index", "Employee/viewEmployeeDay");

        }

        //check username and password
        public bool IsCorrectSystemAdmin(LoginModel model)
        {
            return model.Username == System.Configuration.ConfigurationManager.AppSettings["AdminUser"]
                && model.Password == System.Configuration.ConfigurationManager.AppSettings["AdminPassword"] ? true : false;
        }

        //Logout from information
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Login");
        }

    }
}

TimeAttendence/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div id="mainbox" onclick="openFunction()">&#9776;</div>
    <div id="menu" class="sidemenu">

        @if (Session["username"] != null)
        {
            @Html.ActionLink("Logout", "Logout", "LoginAccount")
        }
        else
        {
            @Html.ActionLink("Scan QRCode", "Index", "Home")
            @Html.ActionLink("Login", "Login", "LoginAccount")
        }

        <a href="#" class="closebtn" onclick="closeFunction()">&times;</a>
    </div>

    <script type="text/javascript">
        function openFunction() {
            document.getElementById("menu").style.width = "300px";
            document.getElementById("mainbox").style.marginLeft = "300px";
        }
        function closeFunction() {
            document.getElementById("menu").style.width = "0px";
            document.getElementById("mainbox").style.marginLeft = "0px";
        }
    </script>

    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>